### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by mmanpreett** [MTACS/Ampere#1]
# Please add a detailed description of the feature you would like added

1: Battery icon remains completely filled even when battery percentage is low or are any random number, it should fill according to battery percentage like original iOS 16.x

2: While charging Bolt icon/symbol should be inside the the battery icon like original iOS 16.x style.

3: Newly added preference page in iOS settings is getting crashed randomly.

**Comment by Levoamphetamine** [comment]
Add a toggle to revert back to the old battery fill method
