### ISSUE TITLE
[support for CarPlay]

### ISSUE THREAD

**Issue by ceedveed** [MTACS/Ampere#11]
# battery icon changes for ampere do not show in CarPlay. CarPlay only shows the default battery icon. BatteryPercentageX shows in CarPlay when I used it in iOS 14: https://cydia.ichitaso.com/depiction/batteryx.html

**Comment by MTACS** [comment]
I'll work on adding it, should be included in the next update

**Comment by ceedveed** [comment]
Thanks for including this in the latest update. I tested it and it shows in CarPlay. iOS 15.1.1
