### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by HeinAtta** [MTACS/Ampere#14]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone 7+]
 - iOS Version: [e.g. iOS 15.6]
 - Ampere version [e.g. 1.0.3]

**Comment by MTACS** [comment]
Could I get more info on what's occurring? There are no details currently
